### ISSUE TITLE
Caching / avoiding needless work

### ISSUE THREAD

**Issue by Haroenv** [withastro/action#60]
I notice that by default, all images are optimised, and regenerated on every build, which actually takes quite a lot of time. Optimising this part of the build would speed up the build immensely (unless images are actually changed of course). 

I was thinking of either having some sort of cache here, or giving up on local images and using a media server, what do you think? Thanks!

**Comment by delucis** [comment]
Astro uses a cache directory inside `node_modules`, so I guess the Action needs to make sure those are cached across builds. I believe there are options for that usually in the Node setup action?

**Comment by Haroenv** [comment]
Seems like that's already set in https://github.com/withastro/action/blob/44cbafd43567733e3b007918c6e0711480560516/action.yml#L76, but I'm definitely still seeing the images being reprocessed every run. Maybe that part isn't cached?

**Comment by delucis** [comment]
If it's caching `node_modules`, then the image cache should definitely come along. You could double check by running `astro build` locally to make sure it's working. You should see the images logged as usual during the build process with something like "reused" at the end of the line. 

If it's working locally, then it may be something to do with how GitHub decides when to reuse a cache (e.g. it could save the cache, but then not use it because it uses a fresh one per branch or something, not sure).

**Comment by Haroenv** [comment]
You're right, locally I also see image optimisation happening on every build, so it's likely something else of configuration and not specific to the GitHub action. I'll close for now but if you know what may be going on, I'm all ears!

The repo I'm working on is https://github.com/abisummers/abisummers.github.io FYI, in case something in the settings may be wrong?

**Comment by delucis** [comment]
Nothing jumps out immediately. It's been a while since I used Yarn and it's also rarer in the Astro community (nom and pnpm tend to be what I see people using most often), so it _might_ be an issue with how Astro handles caching with Yarn specifically? But that's only a wild guess.
